version: '3'
services:
  web:
    image: clarknoah/stillness_sahasrara:v0.0.1
    depends_on:
      - "neo4j"
    ports:
     - "80:3000"
    links:
     - neo4j
  neo4j:
    image: neo4j:latest
    ports:
     - "7474:7474"
     - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/stillness
